# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Example Frame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Example Custom
  pod 'Frames', :path => '../', :testspecs => ['Tests']

  target 'iOS Example FrameUITests' do
    # Pods for testing
  end

end

