platform :ios, '13.0'
install! 'cocoapods', :share_schemes_for_development_pods => true

target 'CheckoutCocoapodsSample' do
  use_frameworks!

  # Pods for CheckoutSDKCocoapodsSample
  pod 'Checkout', :path => '../../../'
end
