# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Example Custom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Example Custom
  pod 'Frames', :path => '../', :testspecs => ['Tests']

  target 'iOS Example CustomUITests' do
    # Pods for testing
  end

  # this block fixes IBDesignables that depend on cocoapods
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
          end
      end
  end
end

