module: Frames
author: Checkout.com
author_url: https://www.checkout.com/
source_host: github
source_host_url: https://github.com/checkout/frames-ios
source_host_files_url: https://github.com/checkout/frames-ios/tree/main
output: .github/docs
theme: .jazzy/.themes/checkout.com
clean: true
documentation: Documentation/**/*.md
min_acl: public
xcodebuild_arguments:
  - -workspace
  - iOS Example Frame/iOS Example Frame.xcworkspace
  - -scheme
  - Frames
  - -destination
  - generic/platform=iOS
