included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - Tests
  - iOS Example
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/Alamofire
  - Source/PhoneNumberKit
identifier_name:
  excluded:
    - id
