name: Publish Frames.podspec

on: workflow_dispatch

jobs:
  publish:
    environment: CocoaPodsRelease
    runs-on: macos-12-xl
    steps:
      - uses: actions/checkout@v3

      - name: Publish Frames.podspec
        run: |
          gem install cocoapods
          pod trunk push Frames.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
