name: Publish Frames.podspec

on: workflow_dispatch

jobs:
  publish:
    environment: CocoaPodsRelease
    runs-on: macos-12-xl
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
#      - name: Check current branch
#        run: |
#          if [[ "${GITHUB_REF#refs/heads/}" != "main" && "${GITHUB_REF#refs/heads/}" != release/* ]]; then
#            echo "This workflow is expected to run on the main or release branch only."
#            exit 1
#          fi

      - name: Publish Frames.podspec
        run: |
          gem install cocoapods
          pod trunk push Frames.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
